<section id="badge">

    <div class="badgeContainer"> <!-- badge "Indépendant" -->

        <div id="independantPicture">

            <img src="./assets/i.png" alt="independant">

        </div>

        <div id="independantBadge">

            <h2>indépendant</h2>
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
            </p>

        </div>
    </div>

    <div class="badgeContainer"> <!-- badge "Union" -->

        <div id="unionPicture">

            <img src="./assets/u.png" alt="union">

        </div>

        <div id="unionBadge">

            <h2>union</h2>
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
            </p>

        </div>
    </div>

    <div class="badgeContainer"> <!-- badge "Mouvement" -->

        <div id="mouvementPicture">

            <img src="./assets/m.png" alt="mouvement">

        </div>

        <div id="mouvementBadge">

            <h2>mouvement</h2>
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
            </p>

        </div>
    </div>

</section>