<section id="badges">
    <div class="badges-container">
        <div class="badge-inde">
            <div class="letter-container">
                <div class="I"></div>
            </div>
            <div class="text-badge">
                <h3>INDEPENDANT</h3>
                <p>Dolor delenit just o dolore et sit et nobis erat diam sed takimata non umy vulputate lorem duo.</p>
            </div>
        </div>
        <div class="badge-inde">
            <div class="letter-container">
                <div class="U"></div>
            </div>
            <div class="text-badge">
                <h3>UNION</h3>
                <p>L’union de notre generation et du monde des adulte renfre les gens moin CON</p>
            </div>
        </div>
        <div class="badge-inde">
            <div class="letter-container">
                <div class="M"></div>
            </div>
            <div class="text-badge">
                <h3>MOUVEMENT</h3>
                <p>Dolor delenit just o dolore et sit et nobis  erat diam sed takimata non umy vulputate lorem duo.</p>
            </div>
        </div>
    </div>
</section>
