<section id="badge">

    <div class="badgeContainer"> <!-- badge "Indépendant" -->

        <div id="independantPicture">

            <img src="./assets/i.png" alt="independant">

        </div>

        <div id="independantBadge">

            <h2>indépendant</h2>
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
            </p>

        </div>
    </div>

    <div class="badgeContainer"> <!-- badge "Union" -->

        <div id="unionPicture">

            <img src="./assets/u.png" alt="union">

        </div>

        <div id="unionBadge">

            <h2>union</h2>
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
            </p>

        </div>
    </div>

    <div class="badgeContainer"> <!-- badge "Mouvement" -->

        <div id="mouvementPicture">

            <img src="./assets/m.png" alt="mouvement">

        </div>

        <div id="mouvementBadge">

            <h2>mouvement</h2>
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium similique voluptatum.
            </p>

        </div>
    </div>

</section>


<section id="badges">
    <div class="badges-container">
        <div class="badge-inde">
            <div class="letter-container">
                <div class="I"></div>
            </div>
            <div class="text-badge">
                <h3>INDEPENDANT</h3>
                <p>Dolor delenit just o dolore et sit et nobis erat diam sed takimata non umy vulputate lorem duo.</p>
            </div>
        </div>
        <div class="badge-inde">
            <div class="letter-container">
                <div class="U"></div>
            </div>
            <div class="text-badge">
                <h3>UNION</h3>
                <p>L’union de notre generation et du monde des adulte renfre les gens moin CON</p>
            </div>
        </div>
        <div class="badge-inde">
            <div class="letter-container">
                <div class="M"></div>
            </div>
            <div class="text-badge">
                <h3>MOUVEMENT</h3>
                <p>Dolor delenit just o dolore et sit et nobis  erat diam sed takimata non umy vulputate lorem duo.</p>
            </div>
        </div>
    </div>
</section>
