<section id="cards-ium">
  <div class="container bord-ium my-5 pt-5 ">
    <!-- cards-IUM -->
    <div class="row gap-ium justify-content-center pt-5">

      <div class="col-4 cards-ium ">
        <div class="">
        <img src="file_assets/I.png" alt="">
        </div>
      </div>

      <div class="col-4 cards-ium ">
        <div class="">
        <img src="file_assets/U.png" alt="">
        </div>
      </div>

      <div class="col-4 cards-ium d-flex justify-content-center ">
        <div class="">
        <img src="file_assets/M.png" alt="">
        </div>
      </div>
    </div>

    <!-- cards-Title -->

    <div class="row gap gap-5 justify-content-center mb-5">

      <div class="col-4 card-title mb-5 ">
        <h3 class="mb-3 title">INDEPENDANT</h3>
        <p class="  p-3">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque vel est eligendi quasi ab ad quod nihil impedit recusandae fugiat ipsam tempore architecto nemo in, dolorem quisquam, voluptates quas odio.</p>
      </div>

      <div class="col-4 card-title mb-5">
        <h3 class="mb-3 title">UNION</h3>
        <p class=" p-3">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque vel est eligendi quasi ab ad quod nihil impedit recusandae fugiat ipsam tempore architecto nemo in, dolorem quisquam, voluptates quas odio.</p>
      </div>

      <div class="col-4 card-title mb-5 ">
        <h3 class="mb-3 title">MOUVEMENT</h3>
        <p class=" p-3">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque vel est eligendi quasi ab ad quod nihil impedit recusandae fugiat ipsam tempore architecto nemo in, dolorem quisquam, voluptates quas odio.</p>  
      </div>
      
    </div>

  </div>

</section>

<style>
  #cards-ium{
    .cards-ium {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 180px;
    height: 180px;
    box-shadow: 0 10px 15px rgba(128, 128, 128, 0.5);
    border-radius: 20px;
    position: relative;
    background-color: white;
    top: 50px;
  }

  .card-title{
    background-color: var(--bg);
    color: white;
    width: 345px;
    height: 365px;
    border-radius:20px ;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }
  
  .title{
    color: var(--IUM);
    padding: 30px 0px 0px 0px;
    
  }

  .bord-ium{
    border-top: 5px solid #0502b7;  
  }

  .gap-ium{
    gap: 200px;
  }
    
  }
  
</style>
