<section id="cards-ium">
  <div class="container bord-ium mt-5 pt-5">
    <!-- cards-IUM -->
    <div class="row  justify-content-center my-5 ">

      <div class="col-4  ">
        
        <div class="row justify-content-center mb-5">
 
          <div class=" d-flex justify-content-center cards-ium mb-2 " >
            <img src="file_assets/I.png" alt="">
          </div>

          <div class=" card-title shadow mb-5  px-5  pt-5 ">
            <h3 class=" title-color text-center py-4 ">INDEPENDANT</h3>
            <p class=" text-center pb-5">Dolor delenit justo dolore et sit et nobis erat diam sed takimata non umy vulputate lorem duo.</p>
          </div>
        </div>

      </div>
      <div class="col-4 ">
        
        <div class="row justify-content-center">
 
          <div class=" d-flex justify-content-center cards-ium mb-2 " >
            <img src="file_assets/I.png" alt="">
          </div>

          <div class=" card-title shadow mb-5  px-5  pt-5 ">
            <h3 class=" title-color text-center py-4 ">UNION</h3>
            <p class=" text-center pb-5">L’union de notre generation et du monde des adulte renfre les gens moin CON</p>
          </div>
        </div>

      </div>
      <div class="col-4 ">
        
        <div class="row justify-content-center">
 
          <div class=" d-flex justify-content-center cards-ium mb-2 " >
            <img src="file_assets/I.png" alt="">
          </div>

          <div class=" card-title shadow mb-5  px-5  pt-5 ">
            <h3 class=" title-color text-center py-4 ">MOUVEMENT</h3>
            <p class=" text-center pb-5">Dolor delenit justo dolore et sit et nobis erat diam sed takimata non umy vulputate lorem duo.</p>
          </div>
        </div>

      </div>

      
      

    </div>

  </div>
</section>

<style>
  .cards-ium {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 180px;
    height: 180px;
    box-shadow: 0 10px 15px rgba(128, 128, 128, 0.5);
    border-radius: 20px;
    position: relative;
    background-color: white;
    top: 40px;
  }

  .card-title {
    background-color: var(--bg);
    border-radius: 20px;
    color: white;
    height: 370px;
    width: 346px;
    
    /* border-radius: 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center; */
    
  }

  .title-color {
    color: var(--IUM);
  }

  .bord-ium {
    border-top: 5px solid #0502b7;
    margin-top: 30px;
    padding-top: 20px;
  }

  .gap-ium {
    gap: 200px;
  }
</style>