<section id="cards-ium">
  <div class="container bord-ium">
    <!-- cards-IUM -->
    <div class="row gap-ium justify-content-center pt-5">

      <div class="col-4 ">
        
        <div class="row justify-content-center">
 
          <div class="bg bg-warning d-flex justify-content-center cards-ium mb-2 " >
            <img src="file_assets/I.png" alt="">
          </div>

          <div class=" card-title shadow mb-5 rounded px-5  ">
            <h3 class=" title-color text-center pt-5 pb-2 ">INDEPENDANT</h3>
            <p class=" pb-5">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque vel est eligendi quasi ab ad quod nihil impedit recusandae fugiat ipsam tempore architecto nemo in, dolorem quisquam, voluptates quas odio.</p>
          </div>
        </div>

      </div>

      
      

    </div>

  </div>
</section>

<style>
  .cards-ium {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 180px;
    height: 180px;
    box-shadow: 0 10px 15px rgba(128, 128, 128, 0.5);
    border-radius: 20px;
    position: relative;
    background-color: white;
    top: 40px;
  }

  .card-title {
    background-color: var(--bg);
    color: white;
    height: 370px;
    
    /* border-radius: 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center; */
    
  }

  .title-color {
    color: var(--IUM);
  }

  .bord-ium {
    border-top: 5px solid #0502b7;
    margin-top: 30px;
    padding-top: 20px;
  }

  .gap-ium {
    gap: 200px;
  }
</style>