<section id="cards-reseaux">
    <div class="container"> 
        <div class="row justify-content-center margin-bottom">
            <div class="col-lg-4 col-md-12 col-12 d-flex justify-content-center mb-5"> 
                <div class="mt-5 border bg-reseaux">
                    <img src="file_assets/instagram-icon.png" alt="logo instagram" width="109" height="109">                                
                    <h4 class="title">INSTAGRAM</h4>
                    <p>Dolor delenit justo dolore et sit et nobis erat diam sed takimata nonumy vulputate lorem duo. Consequat molestie praesent amet voluptua justo sed justo magna lorem stet sit at amet sit diam sed ipsum. Ea nonummy</p>
                </div>
            </div>

            <div class="col-lg-4 col-md-12 col-12 d-flex justify-content-center mb-4">
                <div class=" border bg-reseaux-x">
                    <img src="file_assets/X-icon.png" alt="logo twitter" width="143" height="143">
                    <h4 class="title">TWITTER</h4>
                    <p>Dolor delenit justo dolore et sit et nobis erat diam sed takimata nonumy vulputate lorem duo. Consequat molestie praesent amet voluptua justo sed justo magna lorem stet sit at amet sit diam sed ipsum. Ea nonummy</p>
                </div>
            </div>

            <div class="col-lg-4 col-md-12 col-12 d-flex justify-content-center mb-4">
                <div class="mt-5 border bg-reseaux">
                    <img src="file_assets/linkedin-icon.png" alt="logo linkedin" width="109" height="109">
                    <h4 class="title">LINKEDIN</h4>
                    <p>Dolor delenit justo dolore et sit et nobis erat diam sed takimata nonumy vulputate lorem duo. Consequat molestie praesent amet voluptua justo sed justo magna lorem stet sit at amet sit diam sed ipsum. Ea nonummy</p>    
                </div>
            </div>                                    
        </div>
    </div>
</section>

<style>
    #cards-reseaux .bg-reseaux,
    #cards-reseaux .bg-reseaux-x {
        box-shadow: 0 10px 15px rgba(128, 128, 128, 0.5);
        border-radius: 20px;
        padding: 20px;
        background: var(--bg-resaux);
        text-align: center;
    }

    #cards-reseaux .bg-reseaux {
        width: 358px;
        height: 436px;
    }

    #cards-reseaux .bg-reseaux-x {
        width: 358px;
        height: 542px;
    }

    #cards-reseaux .title {
        padding: 30px;
        color: var(--title-reseau);
    }

    #cards-reseaux p {
        color: white;
        font-weight: bold;
        text-align: justify;
    }

    .margin-bottom{
        margin-bottom: 200px;
    }
</style>
