<section id="reseaux-sociaux">

<div class="  d-flex justify-content-center">

<div class="col-4  card-generation ">

<div class="d-flex justify-content-center ">

<div class="card bg-card" style="width: 18rem;">

<img src="file_assets/instagram-icon.png" class="card-img-top" alt="logo instagramm">

<div class="card-body">

<h5 class="card-title text-center">INSTAGRAM</h5>

<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

</div>

</div>

</div>

</div>

<div class="col-4 card-generation ">

<div class="d-flex justify-content-center ">

<div class="card card-twitter" style="width: 18rem;">

<img src="file_assets/X-icon.png" class="card-img-top" alt="...">

<div class="card-body">

<h5 class="card-title text-center">TWITTER</h5>

<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

</div>

</div>

</div>

</div>

<div class="col-4 card-generation ">

<div class="d-flex justify-content-center ">

<div class="card bg-card" style="width: 18rem;">

<img src="file_assets/Linkedin-icon.png" class="card-img-top" alt="...">

<div class="card-body">

<h5 class="card-title text-center">LINKEDIN</h5>

<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

</div>

</div>

</div>

</div>

</section>

<style>

#reseaux-sociaux{

margin-top: 150px;

margin-bottom: 150px;

.card-twitter{

padding: 30px 30px;

background: var( --bg-resaux);

color: white;

font-weight: bold;

height: 550px;

}

.bg-card{

padding: 30px 30px 40px;

background: var( --bg-resaux);

color: white;

font-weight: bold;

height: 400px;

}

h5{

color: var(--title-reseau);

font-weight: bold;

}

}

</style>