<section id="footer">
    <footer class="custom-footer text-center text-white">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 logo d-flex flex-column align-items-center">
                    <div style="background-image: url(<?= $env_logo ?>); width: 181px; height: 181px; border-radius:15px;"></div>
                    <h2 class="mt-2 mb-3">GENERATION IUM</h2>
                </div>
                <div class="col-12 d-flex justify-content-between">
                    <button onclick="window.location.href = 'https://tyrolium.fr';" type="button" class="btn btn-primary btn-lg mx-2">LEGAL</button>
                    <button onclick="window.location.href = 'https://discord.gg/mtDx9ceS7n';" type="button" class="btn btn-primary btn-lg mx-2">ADHERE</button>
                    <button onclick="window.location.href = 'https://tyrolium.fr/contact';" type="button" class="btn btn-primary btn-lg mx-2">CGU</button>
                </div>
                <div class="col-12 mt-3">
                    <div class="border-top">
                        <h5 class="mt-2 ">Copyright © 2024, All Right Reserved Génération IUM</h5>
                    </div>                        
                </div>
            </div>
        </div>
    </footer>
</section>



<style>
    #footer{

            
    background: var(--bg);
    width:100%;
    height: 400px;
    padding: 20px 0;
   
            



.logo h2 {
    margin: 0;
    line-height: 70px;
    }

.custom-button {
    width: 150px;
    text-align: center;
    }
.border-top{
    border-top: solid 3px white;
}    
    }
</style>