<section id="footer">
    <footer class="custom-footer text-center text-white">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 logo d-flex flex-column align-items-center">
                    <a href="index.php">
                        <img src="<?= $env_logo ?>" alt="Logo" class="mx-2" width="100" height="300">
                    </a>
                    <h4 class="mt-2">GENERATION IUM</h4>
                </div>
                <div class="col-12 d-flex justify-content-between mt-4">
                    <button onclick="window.location.href = 'https://tyrolium.fr';" type="button" class="btn btn-primary btn-lg mx-2">LEGAL</button>
                    <button onclick="window.location.href = 'https://discord.gg/mtDx9ceS7n';" type="button" class="btn btn-primary btn-lg mx-2">ADHERE</button>
                    <button onclick="window.location.href = 'https://tyrolium.fr/contact';" type="button" class="btn btn-primary btn-lg mx-2">CGU</button>
                </div>
                <div class="col-12 mt-4">
                    <div class="border-top">
                        <p>Copyright © 2024, All Right Reserved Génération IUM</p>
                    </div>                        
                </div>
            </div>
        </div>
    </footer>
</section>


<style>
    #footer{

            
    background: var(--bg);
    width:100%;
    height: 300px;
    padding: 20px 0;
   
            

.logo img {
    height: 70px;
    }

.logo h2 {
    margin: 0;
    line-height: 70px;
    }

.custom-button {
    width: 150px;
    text-align: center;
    }
.border-top{
    border-top: solid 3px white;
}    
    }
</style>