<section id="footer">

    <div id="logofooter">
    
        <img src="./assets/logo.png" alt="logo_generation_ium">
        
    </div>
    <div id="titlefooter">

        <h2>Génération ium</h2>

    </div>

    <nav id="navfooter">

        <a href="#">Legal</a>
        <a href="#">Adhèrer</a>
        <a href="#">CGU</a>

    </nav>
    <div id="copyright">

        <p>Copyright © 2024, All Right Reserved Génération IUM </p>

    </div>

</section>