<section id="generation">
  <div class="  d-flex justify-content-center ">

    <div class="col-6 bg-white card-generation shadow mb-5">

      <div class="d-flex justify-content-center ">
        <div class="bg-img my-5 " style="background-image:url('file_assets/title-generation.png')"></div>
      </div>

      <div class="mb-5 mx-5 text-center">
        <p>Le premier mouvement français, pour défendre la nouvelle génération d'entrepreneur, de créateur de contenu, d'artiste et métiers d'internet. Ceux qui ce lève tôt pour leurs projets et objectifs</p>

        <p>Génération IUM veut défendre toute cette parti de notre génération oublier par beaucoup, ceux qui on des objectifs fort, des projets énorme, toute cette parti de génération qui ce lève tôt, celle trop peut défendu a cause de minorité bruyante qui veulent défendre des idée destructeur pour notre société. Nous écoutant ces jeunes réfléchie, qui prenne soins d'eux, de leurs idée, de leurs capacité a réfléchir au de là du politiquement correcte.</p>

        <p>Ce mouvement veut écouter ceux qui bosse dans leurs coins, qui ne dise rien, mais qui font de notre société, une société encore actif et prospère</p>
      </div>

    </div>
  </div>


</section>

<style>
  #generation {
    .bg-img {
      width: 470px;
      height: 66px;
    }

    .card-generation {
      display: flex;
      flex-direction: column;
      justify-content: center;
      border-radius: 20px;
      background-color: white;
      position: relative;
      top: -40px;
    }

  }
</style>