<section id="generation">
    <div class="generationcard">
        <img src="./assets/generation.png" alt="generation_titre">
        <p>
            Le premier mouvement français, pour défendre la nouvelle génération  d'entrepreneur, de créateur de contenu, d'artiste et métiers d'internet.  Ceux qui ce lève tôt pour leurs projets et objectifs.<br><br>   

            Génération IUM veut défendre toute cette parti de notre génération oublier par beaucoup, ceux qui on des objectifs fort, des projets énorme, toute cette parti de génération qui ce lève tôt, celle trop peut  défendu a cause de minorité bruyante qui veulent défendre des idée  destructeur pour notre société. Nous écoutant ces jeunes réfléchie, qui  prenne soins d'eux, de leurs idée, de leurs capacité a réfléchir au de  là du politiquement correcte  <br><br>

            Ce mouvement veut écouter ceux qui bosse dans leurs coins, qui ne dise  rien, mais qui font de notre société, une société encore actif et  prospère
        </p>
    </div>
</section>