<section id="generation">
  <div class="d-flex justify-content-center">
    <div class="  col-lg-7 col-md-8 col-10 bg-white card-generation shadow mb-5">
      <div class="d-flex justify-content-center m-5 ">
        <img src="file_assets/title-generation.png" class="img-fluid" alt="">
      </div>
      <div class=" mx-2 p-5 text-center">
        <p>Le premier mouvement français pour défendre la nouvelle génération d'entrepreneurs, de créateurs de contenu, d'artistes et de métiers d'internet. Ceux qui se lèvent tôt pour leurs projets et objectifs.</p>
        <p>Génération IUM veut défendre toute cette partie de notre génération oubliée par beaucoup, ceux qui ont des objectifs forts, des projets énormes, toute cette partie de génération qui se lève tôt, celle trop peu défendue à cause de minorités bruyantes qui veulent défendre des idées destructrices pour notre société. Nous écoutons ces jeunes réfléchis, qui prennent soin d'eux, de leurs idées, de leur capacité à réfléchir au-delà du politiquement correct.</p>
        <p>Ce mouvement veut écouter ceux qui travaillent dans leur coin, qui ne disent rien, mais qui font de notre société une société encore active et prospère.</p>
      </div>
    </div>
  </div>
</section>

<style>
  #generation 
  .card-generation {
    display: flex;
    flex-direction: column;
    justify-content: center;
    border-radius: 20px;
    background-color: white;
    position: relative;
    top: -50px;
  }

  @media (max-width: 768px) {
   
    .card-generation {
      margin: 0 15px;
    }

    .mb-5.mx-4 {
      margin: 0 10px;
    }
  }

  @media (max-width: 576px) {

    
   
    .card-generation {
      margin: 0 10px;
      
    }

    .mb-5.mx-4 {
      margin: 0 5px;
    }

    p {
      font-size: 14px;
    }
  }


</style>
