<div id="goals">
    <div class="goals">
        <h2>Notre Objectif</h2>
        <p>Dolor delenit justo dolore et sit et nobis erat diam sed takimata nonumy vulputate lorem duo. Consequat molestie praesent amet voluptua justo sed justo magna lorem stet sit at amet sit diam sed ipsum. Ea nonummy amet consetetur ea ut voluptua sea hendrerit ipsum rebum imperdiet et diam ut odio ut rebum diam. Rebum diam ipsum erat feugait kasd dolores lorem lorem et aliquyam kasd labore aliquyam lorem. Amet in amet gubergren aliquam gubergren et et ullamcorper diam. Takimata diam clita kasd stet dolor consetetur magna vero.</p>
    </div>
    <div class="flags"></div>
</div>