<section id="hero">
  <div class="container-fluid">
    <div class="row pt-5">

      <div class=" col-lg-8 col-md-7 col-12 px-0  ">
        <img src="file_assets/hero-image.png" class="img-fluid w-100 h-100" alt="photo-foule">
      </div>

      <div class="  col-lg-4 col-md-5 col-12 bg-login p-5 mt-md-3 mt-0  ">
        <div class=" inner-shadow  bg bg-white rounded  ">
          <div class="text-center p-5 p-md-3 p-lg-2">
            <h2>ADHÉSION</h2>
            <p class="">L'adhésion est 100% gratuite</p>
          </div>

          <form action="" method="" class="d-flex flex-column align-items-center justify-content-center p-3 w-100">
            <input class="mb-4 border-0 inner-shadow w-100 rounded p-3 " type="text" name="email" placeholder="EMAIL">
            <input class="mb-5 border-0 inner-shadow w-100 rounded p-3 " type="text" name="postal" placeholder="CODE POSTAL">
            <button type="submit" class="custom-button">ADHÉRER</button>
          </form>
        </div>
      </div>

    </div>
  </div>
</section>

<style>
  #hero{

  .bg-login {
    background-color: var(--bg);
  }

 
  .inner-shadow {
    box-shadow: inset 0 4px 8px rgba(211, 211, 211, 0.8);
  }

  
  }
</style>
