<section id="hero">
  <div class="container-fluid">
    <div class="row">

      <div class="col-8 p-0">
        <div class="bg-img" style="background-image:url('file_assets/hero-image.png')">
        </div>
      </div>

      <div class="col-4 bg-login d-flex align-items-center justify-content-center">
        <div class="bg-card-login drop-shadow py-5">
          <div class="text-center my-3">
            <h2>ADHÉSION</h2>
            <p>L'adhésion est 100% gratuite</p>
          </div>

          <form action="" method="" class="d-flex flex-column align-items-center justify-content-center">
            <input class="mb-4 ps-2 border-0 inner-shadow" type="text" name="email" placeholder="EMAIL">
            <input class="mb-5 ps-2 border-0 inner-shadow" type="text" name="postal" placeholder="CODE POSTAL">
            <button type="submit" class="custom-button">ADHÉRER</button>
          </form>
        </div>
      </div>

    </div>
  </div>
</section>

<style>
  .bg-img {
    background-repeat: no-repeat;
    background-size: cover;
    width: 100%;
    height: 650px;
  }

  .bg-login {
    background-color: var(--bg);
  }

  .bg-card-login {
    background-color: white;
    border-radius: 20px;
    width: 350px;
    height: auto;
  }

  input {
    width: 280px;
    height: 50px;
    border-radius: 10px;
  }

  .inner-shadow {
    box-shadow: inset 0 4px 8px rgba(211, 211, 211, 0.8);
  }
</style>
