<section id="hero">
  <div class="container-fluid">
    <div class="row">

      <div class="col-xl-8 col-lg-8 col-sm-8 col-12  p-0">
        <div class="bg-img" style="background-image:url('file_assets/hero-image.png')">
        </div>
      </div>

      <div class="col-xl-4 col-lg-4 col-sm-4 col-12 bg-login d-flex align-items-center justify-content-center">
        <div class="bg-card-login drop-shadow py-5 ">
          <div class="text-center my-3">
            <h2>ADHÉSION</h2>
            <p>L'adhésion est 100% gratuite</p>
          </div>

          <form action="" method="" class="d-flex flex-column align-items-center justify-content-center ">
            <input class="mb-4 ps-2 border-0 inner-shadow" type="text" name="email" placeholder="EMAIL">
            <input class="mb-5 ps-2 border-0 inner-shadow" type="text" name="postal" placeholder="CODE POSTAL">
            <button type="submit" class="custom-button">ADHÉRER</button>
          </form>
        </div>
      </div>

    </div>
  </div>
</section>

<style>
  .bg-img {
    background-repeat: no-repeat;
    background-size: cover;
    width: 100%;
    height: 700px;
  }


  .bg-login {
    background-color: var(--bg);
  }

  .bg-card-login {
    background-color: white;
    border-radius: 20px;
    margin-top: 80px;
    width: 350px;
    height: auto;
  }

  input {
    width: 280px;
    height: 50px;
    border-radius: 10px;
    font-size: 16px;
  }

  .inner-shadow {
    box-shadow: inset 0 4px 8px rgba(211, 211, 211, 0.8);
  }

  @media (max-width: 1025px) {
    .bg-img {
      height: 600px;
    }

    .bg-card-login {
    width: 250px;
    height: 400px;
  }
  input {
    width: 200px;
    height: 50px;
    border-radius: 10px;
    font-size: 13px;
  }
  
  .custom-button {
  padding: 5px 30px;
  font-size: 
  13px; 
   
}
  }

 @media (max-width: 992px) {
    .bg-img {
      height: 600px;
    }
    

    .bg-card-login {
    width: 250px;
    height: 400px;
  }
  input {
    width: 220px;
    height: 50px;
    border-radius: 10px;
    font-size: 13px;
  }
}

@media (max-width: 768px) {
    .bg-img {
      height: 600px;
    }
  

  .bg-card-login {
   
    width: 220px;
    height: 400px;
  }
  input {
    width: 180px;
  }
}

@media (max-width: 576px) {
    .bg-img {
      height: 300px;
    }
  

  .bg-card-login {
   
    width: 300px;
    height: 400px;
    margin: 80px 0px;
  }
  input {
    width: 250px;
  }
}

</style>
