<form action="#" method="POST" id="joinForm">
    <h3>ADHESION</h3>
    <p>L'adhesion est 100% gratuite</p>
    <label for="email"></label>
    <input type="text" id="email" name="email" placeholder="EMAIL" class="fields" required>
    <label for="zipcode"></label>
    <input type="text" id="zipcode" name="zipcode" placeholder="CODE POSTAL" class="fields" required>
    <input type="submit" value="ADHERER" class="formButton">
</form>