<section id="navbar">
    <nav class="navbar navbar-expand-lg shadow fixed-top bg bg-white">
        <div class="container">
            <a class="navbar-brand nav" href="#">
                <img src="<?= $env_logo ?>" alt="Logo" width="100" height="90" class="d-inline-block align-text-top">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item d-flex justify-content-end">
                        <button class="custom-button mt-3 mt-lg-0">J'ADHERE</button>
                        
                    </li>

                </ul>

            </div>
        </div>
    </nav>
</section>




<style>
 
</style>