<div id="socialNetworks" class="container">
    <div class="socialNetworks-container">
        <div class="border social-container little">
            <div class="container-picture-social-network instagram"></div>
            <div class="title-container"><h2>INSTAGRAM</h2></div>
            <div class="text">
                <p>Dolor delenit justo dolore et sit et nobis erat diam sed takimata nonumy vulputate lorem duo. Consequat molestie praesent amet voluptua justo sed justo magna lorem stet sit at amet sit diam sed </p>
            </div>
        </div>
        <div class="border social-container big">
            <div class="container-picture-social-network social-X X"></div>
            <div class="title-container mid"><h2>TWITTER</h2></div>
            <div class="text">
                <p>Dolor delenit justo dolore et sit et nobis erat diam sed takimata nonumy vulputate lorem duo. Consequat molestie praesent amet voluptua justo sed justo magna lorem stet sit at amet sit diam sed ipsum. Ea nonummy</p>
            </div> 
        </div>
        <div class="border social-container little">
            <div class="container-picture-social-network linkedin"></div>
            <div class="title-container"><h2>LINKEDIN</h2></div>
            <div class="text">
                <p>Dolor delenit justo dolore et sit et nobis erat diam sed takimata nonumy vulputate lorem duo. Consequat molestie praesent amet voluptua justo sed justo magna lorem stet sit at amet sit diam sed</p>
            </div>
        </div>
    </div>
</div>