<div id="socialNetworks" class="container">
    <div class="row justify-content-center">
        <div class="col-lg-3 border">
            <div class="container-picture-social-network"></div>
            <div><h2>INSTAGRAM</h2></div>
            <div>
                <p>Dolor delenit justo dolore et sit et nobis erat diam sed takimata nonumy vulputate lorem duo. Consequat molestie praesent amet voluptua justo sed justo magna lorem stet sit at amet sit diam sed </p>
            </div>
        </div>
        <div class="col-lg-3 border">
            <div class="container-picture-social-network"></div>
            <div><h2>TWITTER</h2></div>
            <div>
                <p></p>
            </div>Dolor delenit justo dolore et sit et nobis erat diam sed takimata nonumy vulputate lorem duo. Consequat molestie praesent amet voluptua justo sed justo magna lorem stet sit at amet sit diam sed ipsum. Ea nonummy 
        </div>
        <div class="col-lg-3 border">
            <div class="container-picture-social-network"></div>
            <div><h2>LINKEDIN</h2></div>
            <div>
                <p>Dolor delenit justo dolore et sit et nobis erat diam sed takimata nonumy vulputate lorem duo. Consequat molestie praesent amet voluptua justo sed justo magna lorem stet sit at amet sit diam sed</p>
            </div>
        </div>
    </div>
</div>